version: '3.8'

services:
  pdf-converter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/files:/app/backend/files
    environment:
      - NODE_ENV=production
    restart: unless-stopped