apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-converter
  template:
    metadata:
      labels:
        app: pdf-converter
    spec:
      containers:
      - name: pdf-converter
        image: ghcr.io/your-username/pdf-converter:latest # <-- image here 
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: uploads
          mountPath: /app/backend/uploads
        - name: files
          mountPath: /app/backend/files
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: pdf-converter-uploads-pvc
      - name: files
        persistentVolumeClaim:
          claimName: pdf-converter-files-pvc

---
# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pdf-converter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: pdf-converter

---
# kubernetes/persistent-volume-claims.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-converter-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-converter-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi