apiVersion: v1
kind: Service
metadata:
  name: pdf-converter
  labels:
    app: pdf-converter
spec:
  type: LoadBalancer  # This makes the service accessible from outside the cluster
  ports:
    - port: 80        
      targetPort: 3000 
      protocol: TCP
      name: http
  selector:
    app: pdf-converter 